version: 2
jobs:
  build:
    docker:
      - image: felicianotech/docker-hugo:0.37
    working_directory: ~/project
    steps:
      - checkout
      - run:
          name: "Install dependencies"
          working_directory: /
          command: |
            apt-get -y -qq update
            apt-get -y -qq install python3.4-dev
            curl -O https://bootstrap.pypa.io/get-pip.py
            python3.4 get-pip.py --user
            pip install awscli --upgrade --user
      - run:
          name: "Run Hugo"
          command: hugo -v
      - run:
          name: "Test Website"
          command: htmlproofer ~/project/public --allow-hash-href --check-html --empty-alt-ignore
      - deploy:
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
                # Copy over pages - not static js/img/css/downloads
                aws s3 sync --acl "public-read" --sse "AES256" public/ s3://${BUCKET_NAME}/ --exclude 'img' --exclude 'js' --exclude 'downloads' --exclude 'css' --exclude 'post'

                # Ensure static files are set to cache forever - cache for a month --cache-control "max-age=2592000"
                aws s3 sync --cache-control "max-age=2592000" --acl "public-read" --sse "AES256" public/img/ s3://stuartlacy.co.uk.s3-eu-west-2.amazonaws.com/img/
                aws s3 sync --cache-control "max-age=2592000" --acl "public-read" --sse "AES256" public/css/ s3://stuartlacy.co.uk.s3-eu-west-2.amazonaws.com/css/
                aws s3 sync --cache-control "max-age=2592000" --acl "public-read" --sse "AES256" public/js/ s3://stuartlacy.co.uk.s3-eu-west-2.amazonaws.com/js/

                # Downloads binaries, not part of repo - cache at edge for a year --cache-control "max-age=31536000"
                aws s3 sync --cache-control "max-age=31536000" --acl "public-read" --sse "AES256" static/downloads/ s3://stuartlacy.co.uk.s3-eu-west-2.amazonaws.com/downloads/
            fi
